volta install vscode-html-languageserver-bin
volta install typescript
volta install prettier
volta install @fsouza/prettierd./
volta install typescript-language-server
volta install vim-language-server
volta install bash-language-server
volta install yaml-language-server
volta install vscode-json-languageserver
volta install vscode-css-languageserver-bin
volta install pyright